### ISSUE TITLE
Check backward incompatible H2 upgrade since SpringBoot 2.7.0

### ISSUE THREAD

**Issue by bkratz** [workshops-de/Bookshelf_sample_solution#31]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes:
Spring Boot 2.7 has upgraded to H2 2.1.120. H2 2.x is backwards incompatible and fixes a number of security vulnerabilities. See the [H2 changelog](http://www.h2database.com/html/changelog.html) and [migration guide](http://www.h2database.com/html/migration-to-v2.html) for details of the changes and how to handle the upgrade.

Actions needed:
Check all H2 related configurations and Tasks

**Comment by BjoernKW** [comment]
I've double-checked according to the migration guide. There are no incompatibilities affecting our code.
