### ISSUE TITLE
Check conversion from WebSecurityConfigurerAdapter to SecurityFilterChain

### ISSUE THREAD

**Issue by bkratz** [workshops-de/Bookshelf_sample_solution#32]
In the release Notes for SpringBoot v2.7.0 is a statement:
Spring Boot 2.7 upgrades to Spring Security 5.7 which has deprecated WebSecurityConfigurerAdapter. When [configuring Spring Security without WebSecurityConfigurerAdapter](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) and using Spring Boot’s sliced tests such as @WebMvcTest, you may need to make some changes to your application to make your SecurityFilterChain beans available to your tests by @Import ing your security configuration class. See [the reference documentation](https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/howto.html#howto.testing.slice-tests) for further details.

We havet to check, whether our sample solution still works properly.

**Comment by BjoernKW** [comment]
There's no conversion required in our case since we're currently not using `@WebMvcTest` test slices in our tests.
