### ISSUE TITLE
Migrate "Write a test for creating a new book" assignment to MockMvc

### ISSUE THREAD

**Issue by BjoernKW** [workshops-de/Bookshelf_sample_solution#34]
Currently, the assignment uses [REST Assured](https://rest-assured.io/) and `RestAssuredMockMvc`, which creates a dependency to a specific framework not directly related to Spring Boot.

Hence, for the purpose of this workshop, migrating that assignment to MockMvc and plain Spring Boot technologies probably makes sense.

**Comment by bkratz** [comment]
Habe ich am 08.08.2023 umgesetzt.
