### ISSUE TITLE
Identity check issue with Little Snitch and SureFire Booter on macOS

### ISSUE THREAD

**Issue by BjoernKW** [workshops-de/Bookshelf_sample_solution#42]
Starting at the branch with sample solution for "Use a persistent H2 database" (https://github.com/workshops-de/Bookshelf_sample_solution/tree/Use_a_persistent_H2_database ; not sure, why it happens with that branch exactly, because there don't seem to be any relevant changes causing this behaviour there), there's an identity check issue with Little Snitch (application firewall, see https://www.obdev.at/products/littlesnitch/index.html ) and the Surefire Booter on macOS when running `mvn clean install`.

The Maven Surefire plugin forks multiple processes for running integration tests. For each of these forked processes, a separate Surefire Booter JAR file will be created (e.g., surefirebooter8568082848177481578.jar). Because each of these JARs has different name, Little Snitch recognizes those as different processes and there shows a confirmation modal for each Maven test run:

> iTerm via surefirebooter8568082848177481578.jar
> wants to accept an incoming connection from 192.168.1.7 in the local network
> 
> For security reasons, an existing rule for any via-process was not applied to “surefirebooter8568082848177481578.jar”!

By setting the `<forkCount />` for the Maven Surefire plugin to `0`, we can avoid this issue:
`<forkCount>0</forkCount>`

This short video shows the issue as it happens: https://www.loom.com/share/e3f18da9ccbf4999a199687913cc0cf9

Technically, this of course is a problem with Little Snitch, rather than Maven Surefire. However, after having talked to their support they don't see an easy way to alleviate this issue within their software. Hence, I've been using this workaround for the time being:

```
	<!-- Work-around for identity check issue with Little Snitch and SureFire Booter on macOS -->
	<!-- TODO: Remove this segment once that issue is resolved -->
	<profiles>
		<profile>
			<id>macOS</id>
			<activation>
				<os>
					<family>mac</family>
				</os>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<configuration>
							<forkCount>0</forkCount>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

**Comment by khmarbaise** [comment]
I have retested the same setup with Mac...without any appearance of the issue...

**Comment by BjoernKW** [comment]
Apparently, this is related to how H2 is started. The issue first occurs with the **Use_a_persistent_H2_database**, where we're first using a persistent H2 database, rather than an embedded, in-memory one with an H2 server started for external access (e.g., via an IDE). When omitting the `AUTO_SERVER=TRUE` parameter from `spring.datasource.url` in the `application.yml` configuration file, the issue doesn't occur:

```
spring:
  datasource:
    url: jdbc:h2:./testdb;DB_CLOSE_DELAY=-1 # Issue occurs only with jdbc:h2:./testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
```

**Comment by BjoernKW** [comment]
This H2-related behaviour with Maven Surefire makes sense, because of the way the H2 "Automatic Mixed Mode" works: [h2database.com/html/features.html#auto_mixed_mode](http://www.h2database.com/html/features.html#auto_mixed_mode)

The first Maven Surefire process will use the embedded connection, whereas every subsequent forked process will use a server connection, which in turn triggers a Little Snitch connection warning.

**Comment by BjoernKW** [comment]
I've now _fixed_ this on my machine with these two Little Snitch rules as workaround:

<img width="437" alt="Screenshot 2022-09-08 at 16 33 06" src="https://user-images.githubusercontent.com/125270/189150451-c4b6e673-786c-4fe1-a06d-cd87eec3b160.png">
<img width="440" alt="Screenshot 2022-09-08 at 16 33 22" src="https://user-images.githubusercontent.com/125270/189150458-222a1c4c-0162-4f71-8405-5532aadf918b.png">

@khmarbaise Could you maybe check if you have the same or similar rules in your Little Snitch configuration? That'd explain the different behaviour in your environment.
