### ISSUE TITLE
Extend preparation task to cover possible proxy issues

### ISSUE THREAD

**Issue by rweisleder** [workshops-de/Bookshelf_sample_solution#57]
In my workshop one attendee lost the first morning due to company proxy issues.

The preparation task should be extended to cover those issues. For example the task could be to clone an existing repository and run a maven build (which downloads dependencies).

If we want to use ElephantSQL in the future, we could also check if the firewall settings allow port 5432 by creating a JDBC connection.

**Comment by BjoernKW** [comment]
Thanks for that feedback. Today, we encountered a similar issue (albeit with a local Maven installation) in our workshop, too.

I've now extended the "Preparation" task accordingly. Could you please check if the new task description reflects what you had mind for this or if we could add further helpful details?

**Comment by rweisleder** [comment]
Thanks for the quick feedback. I think running `mvn --version` is not enough in this case. First, start.spring.io generates a project which uses the Maven Wrapper, so technically we don't require a global installation of Maven. But if the global installation works, then mvnw should also work. Second, in this case the issue was that Maven could not resolve dependencies because of connection failures.

A long time ago, I wrote something like "`mvn dependency:get -Dartifact=junit:junit:4.12` should work" in a company wiki. Maybe we could add something short like this. And we need to add Maven to the list of required tools.

**Comment by BjoernKW** [comment]
Thanks again for the additional input. That's a useful technique. I've added the second command for verifying the network settings.

Your comment regarding Maven Wrapper is correct, too. However, I've opted against including it at this stage for now, because that'd mean checking out our generating a Spring Boot project first, which might only server to further complicate things.
