### ISSUE TITLE
Improve Jackson ObjectMapper customizations

### ISSUE THREAD

**Issue by BjoernKW** [workshops-de/Bookshelf_sample_solution#73]
Use `Jackson2ObjectMapperBuilderCustomizer` (https://www.baeldung.com/spring-boot-customize-jackson-objectmapper#2-jackson2objectmapperbuildercustomizer ) and / or `Jackson2ObjectMapperBuilder` (
https://www.baeldung.com/spring-boot-customize-jackson-objectmapper#2-jackson2objectmapperbuilder ) instead of `new ObjectMapper()`.

Also see this video for more details on how to use the `Jackson2ObjectMapperBuilder`: https://www.youtube.com/watch?v=BhiF6e24l5k&t=594s

**Comment by bkratz** [comment]
Changed JacksonTestConfiguration to use Jackson2ObjectMapperBuilderCustomizer.
JacksonTestConfiguration is now imported to BookRestControllerIntegrationTest to see the effect. The effect cn only be seen for test usig MockMvc. For sests using RestAssured JSON is always printed out in pretty print style.
