### ISSUE TITLE
Replace RestAssure with the new synchronous RestClient for testing

### ISSUE THREAD

**Issue by BjoernKW** [workshops-de/Bookshelf_sample_solution#76]
See https://spring.io/blog/2023/07/13/new-in-spring-6-1-restclient

**Comment by BjoernKW** [comment]
Using `RestClient` for testing isn't as straightforward and accessible as expected (see https://github.com/workshops-de/Bookshelf_Spring_Boot_workshop_10_01_2024/blob/main/src/test/java/de/workshops/bookshelf/book/BookRestControllerRestClientTest.java, for example). Hence, for the moment, we're probably better off with continuing to use RestAssured.

**Comment by rweisleder** [comment]
Related: https://github.com/spring-projects/spring-framework/issues/31275
